#!/bin/bash

# Transhrimpment Case Study - Digital Investigation Demo
# This script demonstrates the CLI workflow for investigating supply chain fraud

# Change to project root for proper module resolution
cd ../../

# Using existing case study configurations
echo "🔍 Starting Transhrimpment Digital Investigation Demo"
echo "===================================================="
echo ""

REPORT_FILE="case-studies/transhrimpment/report.md"

# Initialize report file
cat > "$REPORT_FILE" << 'EOF'
# Transhrimpment Digital Investigation Report

*Generated by automated CLI analysis*

## Executive Summary

This report documents a digital forensic investigation of the "Transhrimpment" supply chain fraud case using verifiable credentials and cryptographic signatures to detect document tampering and identity theft.

---

EOF

echo "🔍 Starting Transhrimpment Digital Investigation Demo"
echo "=================================================="
echo "📄 Report will be generated in: $REPORT_FILE"

# Ensure output directories exist
mkdir -p case-studies/transhrimpment/{signed,controllers,keys,credentials,presentations}

echo ""
echo "🔍 Step 1: Identify Entities"
echo "============================"
echo "🔒 Reading entity configurations..."
echo "🌐 Generating controller documents..."
echo "📍 Validating and extracting geographic data..."

# Add controller generation section to report
cat >> "$REPORT_FILE" << 'EOF'
## Step 1: Identify Entities

Identifying supply chain entities, gather their addresses, locations and aliases for comparison to supply chain documents:

EOF

# Helper function to run command and capture REAL output for report
run_command_and_report() {
    local description="$1"
    local command="$2"
    local status_emoji="$3"

    echo "Running: $description..."

    # Run command and capture REAL output
    local output
    local exit_code
    output=$(eval "$command" 2>&1)
    exit_code=$?

    # Determine actual status based on exit code
    local actual_status
    if [ $exit_code -eq 0 ]; then
        actual_status="✅"
    else
        actual_status="❌"
    fi

    # Add REAL results to report with collapsible section
    echo "" >> "$REPORT_FILE"
    echo "<details>" >> "$REPORT_FILE"
    echo "<summary>$actual_status $description</summary>" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    echo '```bash' >> "$REPORT_FILE"
    echo "$ $command" >> "$REPORT_FILE"
    echo '```' >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    echo '```' >> "$REPORT_FILE"
    echo "$output" >> "$REPORT_FILE"
    echo '```' >> "$REPORT_FILE"
    if [ $exit_code -ne 0 ]; then
        echo "Exit code: $exit_code" >> "$REPORT_FILE"
    fi
    echo "" >> "$REPORT_FILE"
    echo "</details>" >> "$REPORT_FILE"

    return $exit_code
}

# Generate all controller documents silently
echo "Generating controller documents..."
bun src/cli.ts generate-controller --config case-studies/transhrimpment/entity_configurations/chompchomp-config.json --out case-studies/transhrimpment/controllers/chompchomp-controller.json > /dev/null 2>&1
bun src/cli.ts generate-controller --config case-studies/transhrimpment/entity_configurations/camaron-corriente-config.json --out case-studies/transhrimpment/controllers/camaron-corriente-controller.json > /dev/null 2>&1
bun src/cli.ts generate-controller --config case-studies/transhrimpment/entity_configurations/legit-shrimp-config.json --out case-studies/transhrimpment/controllers/legit-shrimp-controller.json > /dev/null 2>&1
bun src/cli.ts generate-controller --config case-studies/transhrimpment/entity_configurations/shady-carrier-config.json --out case-studies/transhrimpment/controllers/shady-carrier-controller.json > /dev/null 2>&1
bun src/cli.ts generate-controller --config case-studies/transhrimpment/entity_configurations/shady-distributor-config.json --out case-studies/transhrimpment/controllers/shady-distributor-controller.json > /dev/null 2>&1
bun src/cli.ts generate-controller --config case-studies/transhrimpment/entity_configurations/cargo-line-config.json --out case-studies/transhrimpment/controllers/cargo-line-controller.json > /dev/null 2>&1
bun src/cli.ts generate-controller --config case-studies/transhrimpment/entity_configurations/anonymous-distributor-config.json --out case-studies/transhrimpment/controllers/anonymous-distributor-controller.json > /dev/null 2>&1
bun src/cli.ts generate-controller --config case-studies/transhrimpment/entity_configurations/honest-importer-config.json --out case-studies/transhrimpment/controllers/honest-importer-controller.json > /dev/null 2>&1

# Function to extract entity info and GeoJSON preview from validation
extract_entity_geojson() {
    local entity_name="$1"
    local controller_file="$2"

    echo "Identifying $entity_name..."

    # Use the new analyze-controller command to generate entity report
    local entity_report
    entity_report=$(bun src/cli.ts analyze-controller --controller "$controller_file" --schema case-studies/transhrimpment/schemas/controller-document.yaml 2>/dev/null)

    # Replace the generic "Entity Analysis" title with the actual entity name
    entity_report=$(echo "$entity_report" | sed "s/### ✅ Entity Analysis/### ✅ $entity_name/" | sed "s/### ❌ Entity Analysis/### ❌ $entity_name/")

    # Add the entity report to the main report file
    echo "" >> "$REPORT_FILE"
    echo "$entity_report" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
}

echo ""
echo "Identifying entities through controller validation..."

# Extract entity information for each controller
extract_entity_geojson "Chompchomp Ltd" "case-studies/transhrimpment/controllers/chompchomp-controller.json"
extract_entity_geojson "Camarón Corriente S.A." "case-studies/transhrimpment/controllers/camaron-corriente-controller.json"
extract_entity_geojson "Legit Shrimp Ltd" "case-studies/transhrimpment/controllers/legit-shrimp-controller.json"
extract_entity_geojson "Shady Carrier Ltd" "case-studies/transhrimpment/controllers/shady-carrier-controller.json"
extract_entity_geojson "Shady Distributor Ltd" "case-studies/transhrimpment/controllers/shady-distributor-controller.json"
extract_entity_geojson "Cargo Line Ltd" "case-studies/transhrimpment/controllers/cargo-line-controller.json"
extract_entity_geojson "Anonymous Distributor" "case-studies/transhrimpment/controllers/anonymous-distributor-controller.json"
extract_entity_geojson "Honest Importer Inc" "case-studies/transhrimpment/controllers/honest-importer-controller.json"

# Add final summary
echo "" >> "$REPORT_FILE"
cat >> "$REPORT_FILE" << 'EOF'

**🔍 Entity identification completed!**

EOF

echo ""
echo "🔍 Entity identification completed! Report generated at: $REPORT_FILE"
echo "📍 Geographic locations extracted for all entities"
echo "🗺️ Map previews available in report"

# Create resolver cache from all controller documents
echo ""
echo "🗃️  Creating resolver cache from controller documents..."
run_command_and_report "Create resolver cache from controllers" "bun src/cli.ts create-resolver-cache --controllers case-studies/transhrimpment/controllers --out case-studies/transhrimpment/resolver-cache.json" "📦"

echo ""
echo "📋 Step 2: Document Creation (Credential Issuance)"
echo "=================================================="
echo "📄 Issuing verifiable credentials from the Transhrimpment narrative..."
echo "🔐 Using private keys from entity configurations..."
echo "✅ Verifying each credential after issuance..."

# Add Step 2 section to report
cat >> "$REPORT_FILE" << 'EOF'

---

## Step 2: Document Creation (Credential Issuance)

<details>
<summary>📋 Click to expand document creation details</summary>

Issuing verifiable credentials based on the Transhrimpment supply chain narrative.
This includes 8 legitimate documents and 1 fraudulent certificate of origin.
Each credential is cryptographically signed by the appropriate entity using their private keys and verified against their controller documents.

EOF

# Helper function to issue and verify credentials
issue_and_verify_credential() {
    local entity_name="$1"
    local entity_config="$2"
    local credential_template="$3"
    local schema_file="$4"
    local output_file="$5"
    local description="$6"

    echo "📋 Issuing $description..."

    # Template will be created if it doesn't exist using predefined examples
    if [ ! -f "$credential_template" ]; then
        echo "⚠️  Credential template $credential_template not found"
        echo "Please ensure credential templates are created before running this demo"
        return 1
    fi

    # Issue the credential
    local sign_result
    sign_result=$(bun src/cli.ts sign-credential --entity-configuration "$entity_config" --credential "$credential_template" --out "$output_file" 2>&1 | head -16)
    local sign_exit_code=$?

    # Verify the credential using the resolver cache
    local verify_result=""
    local verify_exit_code=1

    if [ $sign_exit_code -eq 0 ] && [ -f "$output_file" ]; then
        verify_result=$(bun src/cli.ts verify-credential --credential "$output_file" --resolver-cache case-studies/transhrimpment/resolver-cache.json 2>&1 | head -16)
        verify_exit_code=$?
    fi

    # Determine status
    local status_emoji="❌"
    if [ $sign_exit_code -eq 0 ] && [ $verify_exit_code -eq 0 ]; then
        status_emoji="✅"
    fi

    # Extract any GeoJSON data from the credential
    local geojson_preview=""
    if [ -f "$output_file" ]; then
        geojson_preview=$(python3 -c "
import json
import sys
try:
    with open('$output_file', 'r') as f:
        cred = json.load(f)
    if 'credentialSubject' in cred and 'features' in cred['credentialSubject']:
        features = cred['credentialSubject']['features']
        if features and len(features) > 0:
            coords = features[0].get('geometry', {}).get('coordinates', [])
            props = features[0].get('properties', {})
            if coords:
                print(f'📍 Location: [{coords[0]}, {coords[1]}]')
                if 'name' in props or 'type' in props:
                    print(f'🏢 Details: {props.get(\"name\", \"\")} ({props.get(\"type\", \"\")})')
except Exception as e:
    pass
" 2>/dev/null)
    fi

    # Add to report with credential content and analysis
    cat >> "$REPORT_FILE" << EOF

### $status_emoji $description

<details>
<summary>Document Verification</summary>

**Verify Command:**
\`\`\`bash
bun src/cli.ts verify-credential --credential $output_file --resolver-cache case-studies/transhrimpment/resolver-cache.json
\`\`\`

**Verify Result:**
\`\`\`
$verify_result
\`\`\`

</details>

EOF

    # Skip credential JSON content - EnvelopedVerifiableCredential format is implementation detail

    # Add GeoJSON preview if available
    if [ -n "$geojson_preview" ]; then
        cat >> "$REPORT_FILE" << EOF
**Geographic Information:**
$geojson_preview

EOF
    fi

    # === PRESENTATION WORKFLOW ===
    # Create and sign presentation for this credential
    if [ $sign_exit_code -eq 0 ] && [ -f "$output_file" ]; then
        # Determine presentation output file
        local base_filename=$(basename "$output_file" .json)
        local presentation_file="case-studies/transhrimpment/presentations/${base_filename}-presentation.json"
        local presentation_template_file="${output_file%.json}-presentation-template.json"

        # Extract holder ID from credential's cnf.kid field using resolver cache
        local holder_id=$(bun src/cli.ts extract-holder-id --credential "$output_file" --resolver-cache case-studies/transhrimpment/resolver-cache.json 2>/dev/null || echo "unknown-holder")

        echo "📋 Creating presentation for $description..."

        # Create presentation template for this specific credential
        cat > "$presentation_template_file" << PRES_EOF
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2"
  ],
  "type": [
    "VerifiablePresentation"
  ],
  "holder": "$holder_id",
  "verifiableCredential": [
    $(cat "$output_file")
  ]
}
PRES_EOF

        # Sign the presentation
        local pres_sign_result
        pres_sign_result=$(bun src/cli.ts sign-presentation --entity-configuration "$entity_config" --presentation "$presentation_template_file" --out "$presentation_file" 2>&1 | head -16)
        local pres_sign_exit_code=$?

        # Verify the presentation
        local pres_verify_result=""
        local pres_verify_exit_code=1
        if [ $pres_sign_exit_code -eq 0 ] && [ -f "$presentation_file" ]; then
            pres_verify_result=$(bun src/cli.ts verify-presentation --presentation "$presentation_file" --resolver-cache case-studies/transhrimpment/resolver-cache.json 2>&1 | head -16)
            pres_verify_exit_code=$?
        fi

        # Determine presentation status
        local pres_status_emoji="❌"
        if [ $pres_sign_exit_code -eq 0 ] && [ $pres_verify_exit_code -eq 0 ]; then
            pres_status_emoji="✅"
        fi

        # Add presentation results to report (will be in Step 3)
        if [ ! -f "${REPORT_FILE}.step3_started" ]; then
            cat >> "$REPORT_FILE" << 'STEP3_EOF'

</details>

---

## Step 3: Document Exchange (Presentations)

<details>
<summary>🔄 Click to expand document exchange details</summary>

Creating and verifying presentations of the issued credentials.
Presentations demonstrate how credentials are shared and verified in real supply chain exchanges.
This step reveals the fraud detection capabilities when forged credentials are presented.

STEP3_EOF
            touch "${REPORT_FILE}.step3_started"
        fi

        cat >> "$REPORT_FILE" << EOF

#### $pres_status_emoji Presentation for $description

<details>
<summary>Presentation Verification</summary>

**Verify Command:**
\`\`\`bash
bun src/cli.ts verify-presentation --presentation $presentation_file --resolver-cache case-studies/transhrimpment/resolver-cache.json
\`\`\`

**Verify Result:**
\`\`\`
$pres_verify_result
\`\`\`

</details>

EOF

        # Skip presentation JSON content - EnvelopedVerifiablePresentation format is implementation detail

        # Clean up presentation template file
        rm -f "$presentation_template_file"
    fi

    return $sign_exit_code
}

# Create credential templates and presentations directories
mkdir -p case-studies/transhrimpment/credential-templates
mkdir -p case-studies/transhrimpment/presentations

echo ""
echo "🏭 Issuing legitimate supply chain credentials per narrative..."

# LEGITIMATE DOCUMENTS (8 total as per README)

# 1. Purchase Order: Chompchomp → Camarón Corriente
issue_and_verify_credential \
    "Chompchomp Ltd" \
    "case-studies/transhrimpment/entity_configurations/chompchomp-config.json" \
    "case-studies/transhrimpment/credential-templates/purchase-order-template.json" \
    "case-studies/transhrimpment/schemas/purchase-order-credential.yaml" \
    "case-studies/transhrimpment/credentials/chompchomp-purchase-order.json" \
    "Purchase Order (Chompchomp → Camarón Corriente)"

# 2. Commercial Invoice: Camarón Corriente → Chompchomp
issue_and_verify_credential \
    "Camarón Corriente S.A." \
    "case-studies/transhrimpment/entity_configurations/camaron-corriente-config.json" \
    "case-studies/transhrimpment/credential-templates/commercial-invoice-template.json" \
    "case-studies/transhrimpment/schemas/commercial-invoice-credential.yaml" \
    "case-studies/transhrimpment/credentials/camaron-corriente-invoice.json" \
    "Commercial Invoice (Camarón Corriente → Chompchomp)"

# 3. Certificate of Origin: Camarón Corriente → Chompchomp
issue_and_verify_credential \
    "Camarón Corriente S.A." \
    "case-studies/transhrimpment/entity_configurations/camaron-corriente-config.json" \
    "case-studies/transhrimpment/credential-templates/certificate-origin-template.json" \
    "case-studies/transhrimpment/schemas/certificate-of-origin-credential.yaml" \
    "case-studies/transhrimpment/credentials/camaron-corriente-origin.json" \
    "Certificate of Origin (Camarón Corriente → Chompchomp)"

# 4. Bill of Lading: Shady Carrier → Chompchomp
issue_and_verify_credential \
    "Shady Carrier Ltd" \
    "case-studies/transhrimpment/entity_configurations/shady-carrier-config.json" \
    "case-studies/transhrimpment/credential-templates/bill-lading-template.json" \
    "case-studies/transhrimpment/schemas/bill-of-lading-credential.yaml" \
    "case-studies/transhrimpment/credentials/shady-carrier-lading.json" \
    "Bill of Lading (Shady Carrier → Chompchomp)"

# 5. Secondary Purchase Order: Anonymous Distributor → Shady Distributor
issue_and_verify_credential \
    "Anonymous Distributor" \
    "case-studies/transhrimpment/entity_configurations/anonymous-distributor-config.json" \
    "case-studies/transhrimpment/credential-templates/secondary-purchase-order-template.json" \
    "case-studies/transhrimpment/schemas/purchase-order-credential.yaml" \
    "case-studies/transhrimpment/credentials/anonymous-distributor-purchase-order.json" \
    "Secondary Purchase Order (Anonymous Distributor → Shady Distributor)"

# 6. Secondary Commercial Invoice: Shady Distributor → Anonymous Distributor
issue_and_verify_credential \
    "Shady Distributor Ltd" \
    "case-studies/transhrimpment/entity_configurations/shady-distributor-config.json" \
    "case-studies/transhrimpment/credential-templates/secondary-commercial-invoice-template.json" \
    "case-studies/transhrimpment/schemas/commercial-invoice-credential.yaml" \
    "case-studies/transhrimpment/credentials/shady-distributor-invoice.json" \
    "Secondary Commercial Invoice (Shady Distributor → Anonymous Distributor)"

# 7. Secondary Bill of Lading: Cargo Line → Anonymous Distributor
issue_and_verify_credential \
    "Cargo Line Ltd" \
    "case-studies/transhrimpment/entity_configurations/cargo-line-config.json" \
    "case-studies/transhrimpment/credential-templates/secondary-bill-lading-template.json" \
    "case-studies/transhrimpment/schemas/bill-of-lading-credential.yaml" \
    "case-studies/transhrimpment/credentials/cargo-line-secondary-lading.json" \
    "Secondary Bill of Lading (Cargo Line → Anonymous Distributor)"

# 8. Stolen Certificate of Origin: Legit Shrimp → Honest Importer (legitimate but will be misused)
issue_and_verify_credential \
    "Legit Shrimp Ltd" \
    "case-studies/transhrimpment/entity_configurations/legit-shrimp-config.json" \
    "case-studies/transhrimpment/credential-templates/stolen-certificate-template.json" \
    "case-studies/transhrimpment/schemas/certificate-of-origin-credential.yaml" \
    "case-studies/transhrimpment/credentials/legit-shrimp-honest-importer-origin.json" \
    "Certificate of Origin (Legit Shrimp → Honest Importer) - WILL BE STOLEN"

echo ""
echo "🚨 Issuing fraudulent credential (for investigation purposes)..."

# FRAUDULENT DOCUMENTS (1 total as per README)

# 9. Fraudulent Certificate of Origin: Shady Distributor forging Legit Shrimp's identity
issue_and_verify_credential \
    "Shady Distributor Ltd" \
    "case-studies/transhrimpment/entity_configurations/shady-distributor-config.json" \
    "case-studies/transhrimpment/credential-templates/fraudulent-origin-template.json" \
    "case-studies/transhrimpment/schemas/certificate-of-origin-credential.yaml" \
    "case-studies/transhrimpment/credentials/shady-distributor-fraudulent-origin.json" \
    "FRAUDULENT Certificate of Origin (Shady Distributor forging Legit Shrimp identity)"

# Add summary section to report
cat >> "$REPORT_FILE" << 'EOF'

</details>

---

**📋 Documentation collection completed!**

EOF

echo ""
echo "📋 Steps 2 & 3: Documentation collection completed!"
echo "✅ 8 legitimate credentials issued per narrative"
echo "🚨 1 fraudulent certificate of origin issued"
echo "🔐 All credentials cryptographically signed and verified"
echo "🔄 9 presentations created and verified for each credential"
echo "📍 Geographic data preserved for route analysis"